version: "3.5"
services:
  poll:
    build: ./poll/
    ports:
      - "5000:80"
    networks:
      - poll-tier
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
  db:
    image: "postgres"
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./db-data:/var/lib/postgresql/data
  worker:
    build: ./worker
    networks:
      - back-tier
networks:
  poll-tier:
    name: poll-tier
  result-tier:
    name: result-tier
  back-tier:
    name: back-tier
volumes:
  db-data:
    name: db-data