version: "3.5"
services:
  poll:
    build: ./poll/
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - DB=redis

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    restart: always
    networks:
      - poll-tier
      - back-tier

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - HOST=db

  db:
    image: "postgres"
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./db-data:/var/lib/postgresql/data

  worker:
    build: ./worker
    networks:
      - back-tier
    environment:
      - POSTGRES=db

networks:
  poll-tier:
    name: poll-tier
  result-tier:
    name: result-tier
  back-tier:
    name: back-tier
volumes:
  db-data:
    name: db-data